require:
- rubocop
- rubocop-rspec
- rubocop-rails
- rubocop-performance

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  RSpec:
    Patterns:
    - '_spec.rb$'
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - Rakefile
    - node_modules/**/*
    - vendor/bundle/**/*
  TargetRubyVersion: 2.6.5

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*.rb'

Metrics/AbcSize:
  Enabled: false
